import { Platform, StyleSheet } from 'react-native';

export const messageComposerStyles = StyleSheet.create({
  container: {
    paddingHorizontal: 2,
    paddingTop: 1,
    paddingBottom: 1,
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 5,
  },
  inputWrapper: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: Platform.OS === 'web' ? 'rgba(11, 20, 44, 0.92)' : 'rgba(11, 20, 44, 0.96)',
    borderRadius: 22,
    paddingLeft: 0,
    paddingRight: 0,
    paddingVertical: 0,
    minHeight: 42,
    borderWidth: Platform.OS === 'web' ? 0 : 1,
    borderColor: 'rgba(125, 211, 252, 0.12)',
    overflow: 'hidden',
    shadowColor: '#081027',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: Platform.OS === 'web' ? 0.14 : 0.28,
    shadowRadius: Platform.OS === 'web' ? 12 : 18,
    elevation: Platform.OS === 'web' ? 3 : 8,
  },
  replyInsideInput: {
    paddingHorizontal: 5,
    paddingTop: 4,
    paddingBottom: 1,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingVertical: 1,
    minHeight: 42,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: '#fff',
    maxHeight: 76,
    minHeight: 22,
    paddingVertical: 0,
    paddingHorizontal: 3,
    textAlignVertical: 'center',
  },
  inlineBtnLeft: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Platform.OS === 'web' ? 'transparent' : 'rgba(255,255,255,0.04)',
    marginRight: 2,
  },
  inlineBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Platform.OS === 'web' ? 'transparent' : 'rgba(255,255,255,0.03)',
    marginLeft: 2,
  },
  actionButton: {
    width: 46,
    height: 46,
  },
  gradientButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#131d5f',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.34,
    shadowRadius: 14,
    elevation: 7,
  },
  micButton: {
    borderWidth: 1.5,
    borderColor: 'rgba(140, 198, 255, 0.22)',
    shadowColor: '#0f2458',
    shadowOpacity: 0.72,
    shadowRadius: 14,
    elevation: 9,
  },
  micContainer: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingWrapper: {
    flex: 1,
  },
  micGlow: {
    position: 'absolute',
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(0, 212, 255, 0.25)',
  },
  editBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(49, 27, 105, 0.34)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginHorizontal: 8,
    marginBottom: 4,
    borderRadius: 14,
    borderLeftWidth: 3,
    borderLeftColor: '#7c5cff',
    gap: 8,
  },
  editBannerText: {
    flex: 1,
  },
  editLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6366f1',
  },
  editContent: {
    fontSize: 13,
    color: '#9ca3af',
    marginTop: 1,
  },
  failedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#dc2626',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
    marginBottom: 4,
  },
  failedBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '600',
  },
  sparkleButton: {
    width: 38,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: Platform.OS === 'web' ? 'transparent' : 'rgba(255,255,255,0.04)',
    borderWidth: Platform.OS === 'web' ? 0 : 1,
    borderColor: 'rgba(125, 211, 252, 0.12)',
  },
  scheduleButton: {
    width: 38,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: Platform.OS === 'web' ? 'transparent' : 'rgba(255,255,255,0.04)',
    borderWidth: Platform.OS === 'web' ? 0 : 1,
    borderColor: 'rgba(125, 211, 252, 0.12)',
  },
});
