import { Platform, StyleSheet } from 'react-native';

const isWeb = Platform.OS === 'web';

export const examGenerationStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextWrap: {
    marginLeft: 12,
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  headerSubtitle: {
    marginTop: 2,
    fontSize: 12,
  },
  contentWrap: {
    flex: 1,
    paddingHorizontal: isWeb ? 12 : 18,
    paddingVertical: isWeb ? 14 : 22,
    alignItems: 'center',
  },
  contentInner: {
    flex: 1,
    width: '100%',
    maxWidth: isWeb ? 980 : 860,
  },
  readyContent: {
    flex: 1,
    width: '100%',
  },
  completionBanner: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  completionBannerCompact: {
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  completionBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  completionText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  doneButton: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  doneButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  doneButtonCompact: {
    alignSelf: 'flex-end',
  },
  exportRow: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  exportRowCompact: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  exportButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  exportButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  exportNotice: {
    flex: 1,
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 14,
  },
  exportNoticeCompact: {
    flex: 0,
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'left',
  },
  modelBadge: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  modelBadgeCompact: {
    alignItems: 'flex-start',
    borderRadius: 14,
    flexDirection: 'column',
  },
  modelBadgeLabel: {
    fontSize: 12,
    fontWeight: '700',
    flexShrink: 0,
  },
  modelBadgeMeta: {
    flex: 1,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'right',
  },
  modelBadgeMetaCompact: {
    textAlign: 'left',
  },
  metaCard: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  metaTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  metaLine: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500',
  },
  studyCoachCard: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  studyCoachRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  studyCoachDay: {
    width: 54,
    fontSize: 12,
    fontWeight: '700',
  },
  studyCoachCopy: {
    flex: 1,
    gap: 2,
  },
  studyCoachFocus: {
    fontSize: 12,
    fontWeight: '600',
  },
  studyCoachHint: {
    fontSize: 11,
    lineHeight: 16,
  },
  auditToggleRow: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  auditToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  auditToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  auditToggleLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
  auditToggleHint: {
    fontSize: 11,
    fontWeight: '500',
  },
  examViewWrap: {
    flex: 1,
  },
  centerBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTitle: {
    marginTop: 14,
    fontSize: 18,
    fontWeight: '700',
  },
  loadingText: {
    marginTop: 8,
    textAlign: 'center',
    fontSize: 14,
  },
  loadingSubtext: {
    marginTop: 8,
    textAlign: 'center',
    fontSize: 12,
  },
  quotaWarningText: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  errorIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTitle: {
    marginTop: 14,
    fontSize: 18,
    fontWeight: '700',
  },
  errorText: {
    marginTop: 8,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
  },
  contextNote: {
    marginTop: 12,
    textAlign: 'center',
    fontSize: 12,
  },
  errorButtons: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 10,
  },
  secondaryButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  primaryButton: {
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
});
