/**
 * K-12 Parent Dashboard Styles
 *
 * Extracted from dashboard.tsx and tuned for #NEXT-GEN visual language.
 */

import { StyleSheet } from 'react-native';

const GLASS_BG = 'rgba(255,255,255,0.05)';
const GLASS_BG_SOFT = 'rgba(255,255,255,0.04)';
const GLASS_BORDER = 'rgba(255,255,255,0.10)';
const GLASS_BORDER_SOFT = 'rgba(255,255,255,0.08)';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  cosmicBackdrop: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  cosmicBackdropFill: {
    ...StyleSheet.absoluteFillObject,
  },
  nebulaGlow: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: '#5A409D',
    opacity: 0.1,
  },
  nebulaTop: {
    width: 280,
    height: 280,
    top: -120,
    right: -80,
  },
  nebulaMid: {
    width: 340,
    height: 340,
    top: '34%',
    left: -180,
    backgroundColor: '#3C8E62',
    opacity: 0.08,
  },
  nebulaBottom: {
    width: 300,
    height: 300,
    bottom: -140,
    right: -120,
    opacity: 0.09,
  },
  starDot: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: '#EAF0FF',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
  },
  fixedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    backgroundColor: 'rgba(15,18,30,0.8)',
  },
  headerLeftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  hamburgerButton: {
    padding: 4,
  },
  headerTitleWrapper: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  scrollContent: {
    paddingHorizontal: 8,
    paddingTop: 0,
  },
  heroSummaryCard: {
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 10,
  },
  heroSummaryTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
    gap: 10,
  },
  heroSummaryTitle: {
    fontSize: 21,
    lineHeight: 26,
    fontWeight: '700',
    marginBottom: 3,
  },
  heroSummarySubtitle: {
    fontSize: 13,
    fontWeight: '500',
  },
  heroSummaryStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: 'rgba(15,18,30,0.32)',
  },
  heroSummaryStat: {
    flex: 1,
    alignItems: 'center',
  },
  heroSummaryValue: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  heroSummaryLabel: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  heroStatDivider: {
    width: 1,
    height: 30,
    backgroundColor: GLASS_BORDER_SOFT,
  },
  currentClassCard: {
    borderRadius: 18,
    marginBottom: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
    elevation: 10,
  },
  currentClassGradient: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    gap: 14,
  },
  currentClassTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  currentClassTitleWrap: {
    flex: 1,
  },
  currentClassEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  currentClassTitle: {
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '700',
    marginBottom: 2,
  },
  currentClassSubtitle: {
    fontSize: 13,
    fontWeight: '500',
  },
  currentClassAverageChip: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgba(15,18,30,0.3)',
    alignItems: 'flex-end',
    minWidth: 88,
  },
  currentClassAverageLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 3,
  },
  currentClassAverageValue: {
    fontSize: 18,
    fontWeight: '700',
  },
  currentClassStatsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
  },
  currentClassStatPill: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: 'rgba(15,18,30,0.3)',
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  currentClassStatValue: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 2,
  },
  currentClassStatLabel: {
    fontSize: 11,
    fontWeight: '600',
  },
  inlineTutorCard: {
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 22,
    elevation: 9,
  },
  inlineTutorGradient: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    gap: 12,
  },
  inlineTutorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  inlineTutorIcon: {
    width: 74,
    height: 62,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -14,
  },
  inlineTutorMascot: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  inlineTutorTextWrap: {
    flex: 1,
  },
  inlineTutorTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 2,
  },
  inlineTutorSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    lineHeight: 18,
  },
  inlineTutorCta: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(15,18,30,0.34)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inlineTutorCtaText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  headerLeft: {
    flex: 1,
  },
  greeting: {
    fontSize: 14,
    marginBottom: 4,
  },
  userName: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 2,
  },
  schoolName: {
    fontSize: 14,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  notificationButton: {
    position: 'relative',
    padding: 8,
  },
  notificationBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  profileButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
  },
  profileGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInitial: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  section: {
    marginBottom: 12,
  },
  sectionHeaderCard: {
    width: '100%',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    backgroundColor: GLASS_BG_SOFT,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.26,
    shadowRadius: 20,
    elevation: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionHeaderTitle: {
    fontSize: 19,
    fontWeight: '700',
  },
  sectionHeaderAction: {
    fontSize: 13,
    fontWeight: '700',
  },
  sectionHeaderHint: {
    fontSize: 13,
    marginTop: 6,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: '700',
    marginBottom: 12,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '500',
  },
  childCard: {
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    backgroundColor: GLASS_BG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.32,
    shadowRadius: 22,
    elevation: 9,
  },
  childCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  childAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  childAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  childAvatarText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  childInfo: {
    flex: 1,
    marginLeft: 14,
  },
  childName: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 2,
  },
  childGrade: {
    fontSize: 14,
  },
  childStats: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  childStat: {
    flex: 1,
    alignItems: 'center',
  },
  childStatValue: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  childStatLabel: {
    fontSize: 12,
  },
  childStatDivider: {
    width: 1,
    height: 30,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  quickActionItem: {
    marginBottom: 2,
  },
  quickActionItemRegular: {
    width: '31.5%',
  },
  quickActionItemCompact: {
    width: '48.5%',
  },
  learningHubGrid: {
    gap: 14,
    marginBottom: 14,
  },
  learningHubHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  learningHubHintText: {
    fontSize: 12,
    fontWeight: '600',
  },
  secondaryToolsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  quickActionCard: {
    width: '100%',
    borderRadius: 16,
    minHeight: 106,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: GLASS_BG_SOFT,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 18,
    elevation: 7,
  },
  quickActionCardRegular: {
    minHeight: 104,
  },
  quickActionCardCompact: {
    minHeight: 98,
  },
  quickActionDisabled: {
    opacity: 0.55,
  },
  quickActionLockBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 15,
  },
  updateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    padding: 14,
    marginBottom: 9,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: GLASS_BG_SOFT,
  },
  updateIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  updateInfo: {
    flex: 1,
  },
  updateChild: {
    fontSize: 12,
    marginBottom: 2,
  },
  updateMessage: {
    fontSize: 14,
    fontWeight: '600',
  },
  updateTime: {
    fontSize: 12,
  },
  eventCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    padding: 14,
    marginBottom: 9,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: GLASS_BG_SOFT,
  },
  eventDate: {
    width: 50,
    height: 50,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  eventDateText: {
    fontSize: 18,
    fontWeight: '700',
  },
  eventMonthText: {
    fontSize: 11,
    fontWeight: '600',
  },
  eventInfo: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  eventTime: {
    fontSize: 13,
  },
  communicationCard: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 22,
    elevation: 9,
  },
  communicationGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  communicationContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  communicationIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  communicationText: {
    flex: 1,
  },
  communicationTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 4,
  },
  communicationSubtitle: {
    color: 'rgba(255, 255, 255, 0.84)',
    fontSize: 13,
  },

  /* ── Child Switcher ── */
  childSwitcherRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  childPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  childPillActive: {
    backgroundColor: 'rgba(90,64,157,0.4)',
    borderColor: '#5A409D',
  },
  childPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.6)',
  },
  childPillTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },

  /* ── Urgent Banner ── */
  urgentBannerContainer: {
    gap: 8,
    marginBottom: 16,
  },
  urgentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    gap: 12,
  },
  urgentIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  urgentTextWrap: {
    flex: 1,
  },
  urgentTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  urgentSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },

  /* ── Activity Feed Timeline ── */
  activityTimelineContainer: {
    gap: 8,
  },
  activityTimelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: GLASS_BG_SOFT,
  },
  activityTimelineIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  activityTimelineInfo: {
    flex: 1,
  },
  activityTimelineChild: {
    fontSize: 12,
    marginBottom: 2,
  },
  activityTimelineMessage: {
    fontSize: 14,
    fontWeight: '600',
  },
  activityTimelineTime: {
    fontSize: 12,
  },

  /* ── Learning Hub ── */
  learningHubCard: {
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 22,
    elevation: 9,
  },
  learningHubGradient: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    gap: 14,
  },
  learningHubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  learningHubMascotWrap: {
    width: 74,
    height: 62,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -14,
  },
  learningHubMascot: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  learningHubTextWrap: {
    flex: 1,
  },
  learningHubTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 2,
  },
  learningHubSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    lineHeight: 18,
  },
  learningHubActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  learningHubActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(15,18,30,0.34)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  learningHubActionText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },

  dashAICard: {
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 20,
  },
  dashAIGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  dashAIContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dashAIIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  dashAIText: {
    flex: 1,
  },
  dashAITitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  dashAISubtitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 13,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    borderRadius: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: GLASS_BORDER_SOFT,
    backgroundColor: GLASS_BG_SOFT,
  },
  emptyStateText: {
    fontSize: 14,
    textAlign: 'center',
  },
});
