import { StyleSheet } from 'react-native';

export const createFinanceControlCenterStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    headerActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    headerActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 6,
      paddingVertical: 4,
    },
    headerActionText: {
      fontSize: 11,
      fontWeight: '600',
    },
    tabRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      paddingHorizontal: 12,
      paddingTop: 6,
      paddingBottom: 6,
    },
    tabButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    tabButtonActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    tabButtonText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '600',
    },
    tabButtonTextActive: {
      color: '#fff',
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
    },
    loaderWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    section: {
      gap: 12,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.text,
    },
    cardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    metricCard: {
      width: '48%',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 14,
      padding: 12,
      backgroundColor: theme.cardBackground,
    },
    metricLabel: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 6,
    },
    metricValue: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.text,
    },
    calloutCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 14,
      padding: 14,
      backgroundColor: theme.cardBackground,
    },
    calloutTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 6,
    },
    calloutText: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    infoBanner: {
      borderWidth: 1,
      borderColor: theme.primary + '40',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: theme.primary + '12',
    },
    infoBannerText: {
      color: theme.text,
      fontSize: 12,
      lineHeight: 17,
    },
    errorCard: {
      borderWidth: 1,
      borderColor: (theme.warning || '#F59E0B') + '55',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: (theme.warning || '#F59E0B') + '16',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    errorText: {
      color: theme.text,
      fontSize: 12,
      flex: 1,
      lineHeight: 17,
    },
    breakdownRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border + '80',
    },
    breakdownLeft: {
      flex: 1,
      paddingRight: 10,
    },
    breakdownLabel: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '700',
    },
    breakdownMeta: {
      color: theme.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    breakdownValue: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '800',
    },
    rowBetween: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    linkText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.primary,
    },
    emptyCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 14,
      backgroundColor: theme.surface,
    },
    emptyText: {
      color: theme.textSecondary,
      fontSize: 13,
    },
    queueCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: theme.cardBackground,
      gap: 4,
    },
    queueTitle: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '700',
    },
    queueSubtext: {
      color: theme.textSecondary,
      fontSize: 12,
    },
    queueMetaRow: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    queueActions: {
      marginTop: 10,
      flexDirection: 'row',
      gap: 8,
    },
    queueSummaryCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: theme.cardBackground,
      gap: 10,
    },
    queueSummaryTitle: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '700',
    },
    queueSummaryChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    queueStageChip: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      backgroundColor: theme.surface,
      paddingHorizontal: 10,
      paddingVertical: 7,
      minWidth: 110,
      gap: 2,
    },
    queueStageChipActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primary + '18',
    },
    queueStageChipLabel: {
      color: theme.text,
      fontSize: 11,
      fontWeight: '700',
    },
    queueStageChipLabelActive: {
      color: theme.primary,
    },
    queueStageChipMeta: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '600',
    },
    queueMismatchChip: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: (theme.warning || '#F59E0B') + '55',
      borderRadius: 999,
      backgroundColor: (theme.warning || '#F59E0B') + '14',
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    queueMismatchChipActive: {
      backgroundColor: theme.warning || '#F59E0B',
      borderColor: theme.warning || '#F59E0B',
    },
    queueMismatchChipText: {
      color: theme.warning || '#F59E0B',
      fontSize: 11,
      fontWeight: '700',
    },
    queueMismatchChipTextActive: {
      color: '#fff',
    },
    queueMonthRow: {
      marginTop: 6,
    },
    queueMonthSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: theme.primary + '55',
      backgroundColor: theme.primary + '12',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    queueMonthSelectorMissing: {
      borderColor: (theme.warning || '#F59E0B') + '55',
      backgroundColor: (theme.warning || '#F59E0B') + '14',
    },
    queueMonthSelectorText: {
      fontSize: 11,
      fontWeight: '700',
    },
    queueMismatchNotice: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: (theme.warning || '#F59E0B') + '55',
      borderRadius: 10,
      backgroundColor: (theme.warning || '#F59E0B') + '12',
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    queueMismatchNoticeText: {
      flex: 1,
      color: theme.text,
      fontSize: 11,
      lineHeight: 15,
    },
    badgeRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    statusBadge: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    statusBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    categoryBadge: {
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
      alignSelf: 'flex-start',
    },
    categoryBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    categoryEditButton: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 5,
      gap: 4,
      marginLeft: 'auto',
    },
    categoryEditText: {
      fontSize: 11,
      fontWeight: '600',
    },
    primaryButton: {
      backgroundColor: theme.primary,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 110,
    },
    primaryButtonText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '700',
    },
    successButton: {
      backgroundColor: theme.success || '#22C55E',
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 130,
    },
    secondaryButton: {
      backgroundColor: theme.surface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingVertical: 9,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 90,
    },
    secondaryButtonText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '700',
    },
    rolePill: {
      backgroundColor: theme.primary + '20',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    rolePillText: {
      fontSize: 11,
      color: theme.primary,
      fontWeight: '700',
    },
    ruleCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: theme.cardBackground,
      gap: 8,
    },
    ruleText: {
      color: theme.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    modalKeyboardAvoid: {
      flex: 1,
    },
    modalCard: {
      backgroundColor: theme.cardBackground,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      padding: 16,
      borderTopWidth: 1,
      borderColor: theme.border,
      maxHeight: '90%',
    },
    modalFormScroll: {
      flexShrink: 1,
    },
    modalFormContent: {
      paddingBottom: 8,
      gap: 8,
    },
    modalTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '800',
    },
    inputLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textSecondary,
      marginTop: 6,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: theme.text,
      backgroundColor: theme.surface,
      fontSize: 14,
    },
    methodChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    methodChip: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 7,
      backgroundColor: theme.surface,
    },
    methodChipActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primary,
    },
    methodChipText: {
      fontSize: 11,
      color: theme.text,
      fontWeight: '700',
    },
    methodChipTextActive: {
      color: '#fff',
    },
    documentLinkButton: {
      marginTop: 10,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
      borderWidth: 1,
      borderColor: theme.primary + '55',
      borderRadius: 999,
      backgroundColor: theme.primary + '14',
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    documentLinkText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: '700',
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
      marginTop: 10,
    },
    salarySummaryCard: {
      borderWidth: 1,
      borderColor: theme.primary + '40',
      backgroundColor: theme.primary + '12',
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 8,
    },
    salarySummaryLabel: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '700',
      marginBottom: 4,
    },
    salarySummaryValue: {
      fontSize: 18,
      color: theme.text,
      fontWeight: '800',
    },
  });
