import { Platform, StyleSheet } from 'react-native';

export const createStyles = (theme: any, insets: { top: number; bottom: number }) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    screenHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingBottom: 12,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
    },
    headerIconButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    screenHeaderTitle: {
      fontSize: 18,
      fontWeight: '800',
    },
    statsBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingVertical: 16,
      marginHorizontal: 16,
      marginTop: 8,
      borderRadius: 12,
    },
    statItem: {
      alignItems: 'center',
    },
    statValue: {
      fontSize: 24,
      fontWeight: '700',
    },
    statLabel: {
      fontSize: 12,
      marginTop: 2,
    },
    statDivider: {
      width: 1,
      height: 32,
    },
    queueTabs: {
      flexDirection: 'row',
      gap: 8,
      marginHorizontal: 16,
      marginTop: 12,
    },
    queueTab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 10,
      gap: 8,
    },
    queueTabText: {
      fontSize: 13,
      fontWeight: '700',
    },
    queueBadge: {
      minWidth: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
    },
    queueBadgeText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '700',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginTop: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      gap: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
    },
    filterTabs: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 8,
    },
    filterTab: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: 'transparent',
    },
    filterTabText: {
      fontSize: 14,
      fontWeight: '500',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    errorText: {
      marginTop: 12,
      fontSize: 16,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 16,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
    },
    retryButtonText: {
      color: '#fff',
      fontWeight: '600',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 40,
    },
    emptyText: {
      marginTop: 16,
      fontSize: 16,
      textAlign: 'center',
    },
    listContent: {
      padding: 16,
      paddingBottom: insets.bottom + 20,
    },
    card: {
      borderRadius: 12,
      borderWidth: 1,
      marginBottom: 12,
      overflow: 'hidden',
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 12,
    },
    cardHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      gap: 4,
    },
    statusText: {
      fontSize: 12,
      fontWeight: '600',
    },
    dateText: {
      fontSize: 12,
    },
    viewButton: {
      padding: 8,
    },
    cardContent: {
      paddingHorizontal: 12,
      paddingBottom: 12,
      gap: 8,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    infoLabel: {
      fontSize: 13,
    },
    infoValue: {
      fontSize: 14,
      fontWeight: '500',
      flex: 1,
    },
    categoryBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      gap: 4,
    },
    categoryBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    categoryEditButton: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      gap: 3,
      marginLeft: 'auto',
    },
    categoryEditText: {
      fontSize: 11,
      fontWeight: '600',
    },
    monthPickerButton: {
      marginLeft: 4,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    monthPickerButtonText: {
      fontSize: 11,
      fontWeight: '700',
    },
    cardActions: {
      flexDirection: 'row',
      padding: 12,
      gap: 12,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0,0,0,0.1)',
    },
    actionButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      borderRadius: 8,
      gap: 6,
    },
    rejectButton: {
      borderWidth: 1,
      backgroundColor: 'transparent',
    },
    approveButton: {
      borderWidth: 0,
    },
    actionButtonText: {
      fontSize: 14,
      fontWeight: '600',
    },
    reviewNotes: {
      margin: 12,
      marginTop: 0,
      padding: 10,
      borderRadius: 8,
    },
    reviewNotesLabel: {
      fontSize: 12,
      marginBottom: 4,
    },
    reviewNotesText: {
      fontSize: 13,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      width: '100%',
      maxWidth: Platform.OS === 'web' ? 520 : 400,
      borderRadius: 16,
      padding: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 8,
    },
    modalSubtitle: {
      fontSize: 14,
      marginBottom: 16,
    },
    reasonInput: {
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      fontSize: 14,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    receiptInput: {
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      fontSize: 14,
      marginBottom: 12,
      minWidth: 0,
      width: '100%',
    },
    receiptInputSmall: {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: Platform.OS === 'web' ? 180 : 0,
      minWidth: 0,
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      fontSize: 14,
    },
    receiptRow: {
      flexDirection: 'row',
      flexWrap: Platform.OS === 'web' ? 'wrap' : 'nowrap',
      gap: 12,
      marginBottom: 12,
    },
    receiptViewButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderRadius: 10,
      paddingVertical: 10,
      gap: 6,
      marginTop: 4,
      marginBottom: 12,
    },
    receiptViewText: {
      fontSize: 14,
      fontWeight: '600',
    },
    modalActions: {
      flexDirection: 'row',
      flexWrap: Platform.OS === 'web' ? 'wrap' : 'nowrap',
      marginTop: 16,
      gap: 12,
    },
    modalButton: {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: Platform.OS === 'web' ? 120 : 0,
      minWidth: Platform.OS === 'web' ? 110 : 0,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
    },
    cardHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    modalCancelButton: {
      borderWidth: 1,
    },
    modalRejectButton: {},
    modalButtonText: {
      fontSize: 15,
      fontWeight: '600',
    },
  });
