import { StyleSheet } from 'react-native';

export const createStyles = () =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#0b1220',
    },
    loadingContainer: {
      flex: 1,
      backgroundColor: '#0b1220',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      paddingHorizontal: 20,
    },
    loadingText: {
      color: '#9CA3AF',
      fontSize: 15,
      textAlign: 'center',
    },
    errorCard: {
      backgroundColor: '#111827',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#7f1d1d',
      padding: 18,
      width: '100%',
      maxWidth: 480,
      alignItems: 'center',
      gap: 10,
    },
    errorTitle: {
      color: '#FCA5A5',
      fontSize: 18,
      fontWeight: '800',
      textAlign: 'center',
    },
    errorMessage: {
      color: '#D1D5DB',
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    retryButton: {
      backgroundColor: '#00f5ff',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
      marginTop: 4,
    },
    retryButtonText: {
      color: '#000',
      fontWeight: '700',
      fontSize: 14,
    },
    scrollContainer: {
      padding: 16,
      paddingBottom: 24,
      gap: 12,
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: '#FFFFFF',
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 15,
      color: '#9CA3AF',
      textAlign: 'center',
      lineHeight: 21,
      marginTop: 6,
    },
    plainHeader: {
      paddingVertical: 8,
    },
    sourceTag: {
      marginTop: 8,
      alignSelf: 'center',
      backgroundColor: '#111827',
      borderWidth: 1,
      borderColor: '#1f2937',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    sourceTagText: {
      color: '#93C5FD',
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    schoolTypeInfo: {
      backgroundColor: '#111827',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#1f2937',
      padding: 12,
      gap: 4,
    },
    schoolTypeLabel: {
      color: '#00f5ff',
      fontSize: 14,
      fontWeight: '700',
    },
    schoolTypeDescription: {
      color: '#9CA3AF',
      fontSize: 13,
      lineHeight: 19,
    },
    existingSubscriptionCard: {
      backgroundColor: '#111827',
      borderRadius: 12,
      padding: 20,
      borderWidth: 1,
      borderColor: '#10b981',
      gap: 10,
    },
    existingTitle: {
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: '800',
      textAlign: 'center',
    },
    existingSubtitle: {
      color: '#9CA3AF',
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 8,
    },
    subscriptionInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#1f2937',
      paddingVertical: 8,
    },
    infoLabel: {
      color: '#9CA3AF',
      fontSize: 13,
      fontWeight: '600',
    },
    infoValue: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
      textTransform: 'capitalize',
    },
    primaryButton: {
      backgroundColor: '#00f5ff',
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 8,
    },
    primaryButtonText: {
      color: '#000',
      fontWeight: '800',
      fontSize: 15,
    },
    secondaryButton: {
      borderWidth: 1,
      borderColor: '#334155',
      backgroundColor: '#0f172a',
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
    },
    secondaryButtonText: {
      color: '#CBD5E1',
      fontWeight: '700',
      fontSize: 14,
    },
    toggleRow: {
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      marginTop: 4,
    },
    toggleBtn: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: '#1f2937',
      backgroundColor: '#0f172a',
    },
    toggleBtnActive: {
      backgroundColor: '#00f5ff',
      borderColor: '#00f5ff',
    },
    toggleBtnText: {
      color: '#9CA3AF',
      fontWeight: '700',
      fontSize: 13,
    },
    toggleBtnTextActive: {
      color: '#000',
    },
    overageCard: {
      backgroundColor: '#111827',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#155e75',
      padding: 14,
      gap: 10,
    },
    overageTitle: {
      color: '#E0F2FE',
      fontSize: 16,
      fontWeight: '800',
    },
    overageText: {
      color: '#BAE6FD',
      fontSize: 13,
      lineHeight: 19,
    },
    overageActions: {
      gap: 8,
      marginTop: 2,
    },
    overageButton: {
      backgroundColor: '#0e7490',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      alignItems: 'center',
    },
    overageButtonSecondary: {
      backgroundColor: '#164e63',
    },
    overageButtonText: {
      color: '#ECFEFF',
      fontWeight: '700',
      fontSize: 13,
      textAlign: 'center',
    },
    plansContainer: {
      gap: 4,
    },
    noPlansCard: {
      backgroundColor: '#111827',
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: '#1f2937',
      alignItems: 'center',
    },
    noPlansText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 4,
      textAlign: 'center',
    },
    noPlansSubtext: {
      color: '#9CA3AF',
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 19,
    },
    backLink: {
      alignSelf: 'center',
      paddingVertical: 10,
      paddingHorizontal: 16,
      marginTop: 2,
    },
    backLinkText: {
      color: '#93C5FD',
      fontWeight: '700',
      fontSize: 14,
    },
    divider: {
      height: 1,
      backgroundColor: '#1f2937',
      marginVertical: 4,
    },
    headingLabel: {
      color: '#CBD5E1',
      fontSize: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    mutedPill: {
      alignSelf: 'center',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: '#334155',
      paddingHorizontal: 12,
      paddingVertical: 5,
      backgroundColor: '#0f172a',
    },
    mutedPillText: {
      color: '#94A3B8',
      fontSize: 12,
      fontWeight: '600',
    },
  });
