import type { AdminOrgTypeV1, AdminTaskPack } from './types';

const SHARED_LANE_ROUTES: AdminTaskPack['laneRoutes'] = {
  hiring: '/screens/admin/manage-join-requests',
  admissions: '/screens/admin/manage-join-requests',
  finance_ops: '/screens/admin/fee-management',
};

export const DEFAULT_ADMIN_TASK_PACKS: Record<AdminOrgTypeV1, AdminTaskPack> = {
  preschool: {
    version: 'v1',
    orgType: 'preschool',
    title: 'Preschool Admin Ops',
    subtitle: 'Daily school operations with principal escalation controls',
    laneRoutes: SHARED_LANE_ROUTES,
    tasks: [
      {
        id: 'staff_screening',
        title: 'Staff Screening',
        description: 'Review teacher/admin invites and document readiness.',
        icon: 'people-outline',
        route: '/screens/admin/manage-join-requests',
        category: 'hiring',
        priority: 'high',
        badgeKey: 'pending_hiring',
      },
      {
        id: 'parent_link_requests',
        title: 'Parent Link Requests',
        description: 'Screen parent joins and guardian claim requests.',
        icon: 'link-outline',
        route: '/screens/admin/manage-join-requests',
        category: 'admissions',
        priority: 'high',
        badgeKey: 'pending_admissions',
      },
      {
        id: 'admissions_intake',
        title: 'Admissions Intake',
        description: 'Track registration pipeline and handoff for approvals.',
        icon: 'person-add-outline',
        route: '/screens/principal-registrations',
        category: 'admissions',
        priority: 'normal',
      },
      {
        id: 'payment_ops',
        title: 'Payment Ops',
        description: 'Triage POP/payment exceptions and outstanding fees.',
        icon: 'card-outline',
        route: '/screens/admin/fee-management',
        category: 'finance',
        priority: 'normal',
        badgeKey: 'pending_finance',
      },
      {
        id: 'petty_cash_request',
        title: 'Petty Cash Request',
        description: 'Submit operational spending requests to principal for approval.',
        icon: 'wallet-outline',
        route: '/screens/petty-cash-request',
        category: 'finance',
        priority: 'normal',
      },
      {
        id: 'daily_ops',
        title: 'Daily Ops',
        description: 'Address attendance and classroom operations issues.',
        icon: 'checkbox-outline',
        route: '/screens/attendance-history',
        category: 'operations',
        priority: 'normal',
        badgeKey: 'pending_ops',
      },
      {
        id: 'cleaning_roster',
        title: 'Cleaning Roster',
        description: 'Assign teacher cleaning shifts and track completion.',
        icon: 'sparkles-outline',
        route: '/screens/cleaning-roster',
        category: 'operations',
        priority: 'normal',
      },
      {
        id: 'communications_ops',
        title: 'Comms Ops',
        description: 'Prepare announcements and policy communications.',
        icon: 'megaphone-outline',
        route: '/screens/principal-announcement',
        category: 'communications',
        priority: 'low',
      },
      {
        id: 'dash_tutor',
        title: 'Start Tutor Session',
        description: 'Launch interactive tutor mode for guided learning.',
        icon: 'school-outline',
        route: '/screens/dash-tutor',
        category: 'operations',
        priority: 'low',
      },
    ],
  },
  k12_school: {
    version: 'v1',
    orgType: 'k12_school',
    title: 'K-12 Admin Ops',
    subtitle: 'Phase-aware administration with staffing and exception management',
    laneRoutes: SHARED_LANE_ROUTES,
    tasks: [
      {
        id: 'staff_screening_phase',
        title: 'Phase Staffing',
        description: 'Screen staffing by grade/phase requirements.',
        icon: 'people-outline',
        route: '/screens/admin/manage-join-requests',
        category: 'hiring',
        priority: 'high',
        badgeKey: 'pending_hiring',
      },
      {
        id: 'enrollment_intake',
        title: 'Enrollment Intake',
        description: 'Screen parent/learner joins and route to admissions.',
        icon: 'person-add-outline',
        route: '/screens/admin/manage-join-requests',
        category: 'admissions',
        priority: 'high',
        badgeKey: 'pending_admissions',
      },
      {
        id: 'aftercare_extramural_ops',
        title: 'Aftercare & Extramural',
        description: 'Manage aftercare and activity operations.',
        icon: 'time-outline',
        route: '/screens/aftercare-admin',
        category: 'operations',
        priority: 'normal',
      },
      {
        id: 'fee_pop_exceptions',
        title: 'Fee / POP Exceptions',
        description: 'Triage payment proofs and fee exceptions.',
        icon: 'cash-outline',
        route: '/screens/admin/fee-management',
        category: 'finance',
        priority: 'normal',
        badgeKey: 'pending_finance',
      },
      {
        id: 'petty_cash_request',
        title: 'Petty Cash Request',
        description: 'Submit operational spending requests to principal for approval.',
        icon: 'wallet-outline',
        route: '/screens/petty-cash-request',
        category: 'finance',
        priority: 'normal',
      },
      {
        id: 'attendance_timetable_exceptions',
        title: 'Attendance / Timetable',
        description: 'Resolve daily attendance and timetable exceptions.',
        icon: 'calendar-outline',
        route: '/screens/attendance',
        category: 'operations',
        priority: 'normal',
        badgeKey: 'pending_ops',
      },
      {
        id: 'cleaning_roster',
        title: 'Cleaning Roster',
        description: 'Assign teacher cleaning shifts and track completion.',
        icon: 'sparkles-outline',
        route: '/screens/cleaning-roster',
        category: 'operations',
        priority: 'low',
      },
      {
        id: 'report_policy_comms',
        title: 'Reports & Policy',
        description: 'Coordinate report and policy communication cycles.',
        icon: 'document-text-outline',
        route: '/screens/principal-report-review',
        category: 'communications',
        priority: 'low',
      },
      {
        id: 'dash_tutor',
        title: 'Start Tutor Session',
        description: 'Launch interactive tutor mode for guided learning.',
        icon: 'school-outline',
        route: '/screens/dash-tutor',
        category: 'operations',
        priority: 'low',
      },
    ],
  },
};
