/**
 * Styles for the StudentFeeManagement screen.
 * Extracted per WARP.md § StyleSheet >200 lines.
 */
import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean, insets: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: insets.bottom + 24,
  },
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  pageHeaderBack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: theme.primary + '15',
  },
  pageHeaderBackText: {
    color: theme.text,
    fontSize: 12,
    fontWeight: '700',
  },
  pageHeaderTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.textSecondary,
  },
  pageHeaderSpacer: {
    width: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: theme.textSecondary,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.text,
    marginTop: 16,
  },
  backButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: theme.primary,
    borderRadius: 8,
  },
  backButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  studentCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  studentInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.primary + '20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.primary,
  },
  studentDetails: {
    flex: 1,
    marginLeft: 12,
  },
  studentName: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
  },
  studentMeta: {
    fontSize: 14,
    color: theme.textSecondary,
    marginTop: 2,
  },
  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusPillActive: {
    backgroundColor: theme.success + '1A',
  },
  statusPillInactive: {
    backgroundColor: theme.warning + '1F',
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  statusPillTextActive: {
    color: theme.success,
  },
  statusPillTextInactive: {
    color: theme.warning,
  },
  parentNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    flexWrap: 'wrap',
  },
  parentNoticeText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  parentInviteButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: theme.primary + '15',
  },
  parentInviteText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  enrollmentRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  enrollmentLabel: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  enrollmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: theme.primary + '15',
  },
  enrollmentButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.primary,
  },
  registrationCard: {
    marginTop: 12,
    borderRadius: 12,
    padding: 12,
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.border + '80',
  },
  registrationHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  registrationTitle: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: '600',
  },
  registrationAmount: {
    marginTop: 2,
    fontSize: 15,
    fontWeight: '700',
    color: theme.text,
  },
  registrationStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  registrationStatusBadgePaid: {
    backgroundColor: theme.success + '1A',
  },
  registrationStatusBadgeUnpaid: {
    backgroundColor: theme.warning + '1F',
  },
  registrationStatusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  registrationStatusTextPaid: {
    color: theme.success,
  },
  registrationStatusTextUnpaid: {
    color: theme.warning,
  },
  registrationActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  registrationActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 8,
  },
  registrationMarkPaidButton: {
    backgroundColor: theme.success + '15',
  },
  registrationMarkUnpaidButton: {
    backgroundColor: theme.warning + '15',
  },
  registrationReceiptButton: {
    backgroundColor: theme.primary + '12',
  },
  registrationMarkPaidText: {
    color: theme.success,
    fontSize: 12,
    fontWeight: '700',
  },
  registrationMarkUnpaidText: {
    color: theme.warning,
    fontSize: 12,
    fontWeight: '700',
  },
  registrationReceiptText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  changeClassButton: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: theme.primary + '10',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  changeClassButtonDisabled: {
    opacity: 0.5,
  },
  changeClassText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
  },
  syncTuitionButton: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: (theme.info || theme.primary) + '14',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  syncTuitionText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.info || theme.primary,
  },
  markInactiveButton: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: theme.warning + '18',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  markInactiveText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.warning,
  },
  inactiveInfoBanner: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: theme.warning + '12',
    alignSelf: 'stretch',
  },
  inactiveInfoText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: theme.warning,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
  },
  summaryLabel: {
    fontSize: 12,
    color: theme.textSecondary,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '700',
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 12,
  },
  timelineLoadingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: theme.card,
  },
  timelineLoadingText: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: '600',
  },
  timelineEmptyCard: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: theme.card,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timelineEmptyText: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: '600',
  },
  timelineCard: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.border + '80',
  },
  timelineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  timelineAction: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.text,
  },
  timelineDate: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: '600',
  },
  timelineReason: {
    fontSize: 13,
    color: theme.text,
    marginBottom: 6,
    lineHeight: 18,
  },
  timelineMeta: {
    fontSize: 12,
    color: theme.textSecondary,
    lineHeight: 16,
  },
  contextBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: theme.primary + '12',
    borderWidth: 1,
    borderColor: theme.primary + '30',
    marginBottom: 12,
  },
  contextBannerText: {
    flex: 1,
    fontSize: 12,
    color: theme.primary,
    fontWeight: '600',
    lineHeight: 17,
  },
  contextBannerAction: {
    marginTop: 2,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: theme.primary + '1A',
  },
  contextBannerActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.primary,
  },
  roleScopeNotice: {
    marginBottom: 14,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: theme.warning + '12',
    borderWidth: 1,
    borderColor: theme.warning + '30',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  roleScopeNoticeText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: theme.warning,
    lineHeight: 17,
  },
  correctionGuideCard: {
    marginBottom: 14,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border + '88',
    gap: 6,
  },
  correctionGuideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  correctionGuideTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.text,
  },
  correctionGuideStep: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.textSecondary,
    lineHeight: 17,
  },
  correctionGuideMeta: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
    color: theme.warning,
  },
  recomputeButton: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 10,
    paddingVertical: 10,
    backgroundColor: (theme.info || theme.primary) + '14',
  },
  recomputeButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.info || theme.primary,
  },
  emptyFees: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 32,
    alignItems: 'center',
  },
  emptyFeesText: {
    fontSize: 14,
    color: theme.textSecondary,
    marginTop: 8,
  },
  emptyFeesHint: {
    fontSize: 12,
    color: theme.textSecondary,
    marginTop: 6,
    textAlign: 'center',
  },
  generateFeesButton: {
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: theme.primary + '20',
  },
  generateFeesText: {
    color: theme.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  openFeeSetupButton: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: theme.textSecondary + '20',
  },
  openFeeSetupText: {
    color: theme.textSecondary,
    fontWeight: '700',
    fontSize: 12,
  },
  overdueSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  overdueSectionHeaderText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.error,
  },
  overdueSectionBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: theme.error + '1A',
  },
  overdueSectionBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.error,
  },
  pendingSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  pendingSectionHeaderText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.warning,
  },
  batchActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: theme.error + '14',
    borderWidth: 1,
    borderColor: theme.error + '30',
  },
  batchActionButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.error,
  },
  feeCard: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  feeCardOverdue: {
    borderLeftWidth: 4,
    borderLeftColor: theme.error,
  },
  feeCardPending: {
    borderLeftWidth: 4,
    borderLeftColor: theme.warning,
  },
  feeCardPaid: {
    borderLeftWidth: 4,
    borderLeftColor: theme.success,
  },
  feeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  feeDescription: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
  },
  feeDueDate: {
    fontSize: 13,
    color: theme.textSecondary,
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  feeAmounts: {
    backgroundColor: theme.background,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  amountLabel: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  amountValue: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text,
  },
  finalAmount: {
    fontSize: 15,
    fontWeight: '700',
  },
  waiverNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  waiverNoteText: {
    fontSize: 12,
    color: theme.textSecondary,
    fontStyle: 'italic',
    flex: 1,
  },
  feeActions: {
    flexDirection: 'row',
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
  },
  controlDisabled: {
    opacity: 0.5,
  },
  waiveButton: {
    backgroundColor: '#6B7280' + '15',
  },
  waiveButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  adjustButton: {
    backgroundColor: theme.primary + '15',
  },
  adjustButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
  },
  rescheduleButton: {
    backgroundColor: (theme.info || theme.primary) + '15',
  },
  rescheduleButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.info || theme.primary,
  },
  paidButton: {
    backgroundColor: theme.success + '15',
  },
  paidButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.success,
  },
  receiptButton: {
    backgroundColor: theme.primary + '12',
  },
  receiptButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
  },
  unpaidButton: {
    backgroundColor: theme.warning + '15',
  },
  unpaidButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.warning,
  },
  deleteButton: {
    backgroundColor: theme.error + '14',
  },
  deleteButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.error,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: theme.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: insets.bottom + 24,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.text,
  },
  modalSubtitle: {
    fontSize: 14,
    color: theme.textSecondary,
    marginBottom: 20,
  },
  waiveTypeRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  waiveTypeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: theme.border,
    alignItems: 'center',
  },
  waiveTypeButtonActive: {
    borderColor: theme.primary,
    backgroundColor: theme.primary + '10',
  },
  waiveTypeText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  waiveTypeTextActive: {
    color: theme.primary,
  },
  inputGroup: {
    marginBottom: 16,
  },
  classFeeHintText: {
    marginTop: 8,
    fontSize: 12,
    color: theme.textSecondary,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 8,
  },
  input: {
    backgroundColor: theme.background,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: theme.text,
    borderWidth: 1,
    borderColor: theme.border,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  submitButton: {
    backgroundColor: theme.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  classOptions: {
    marginBottom: 20,
  },
  classOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: theme.background,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  classOptionSelected: {
    borderColor: theme.primary,
    backgroundColor: theme.primary + '10',
  },
  classOptionText: {
    fontSize: 16,
    color: theme.text,
  },
  classOptionTextSelected: {
    fontWeight: '600',
    color: theme.primary,
  },
});
